# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 🏗️🧪🍂 Build & Test branches
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: write
  checks: write
  security-events: write

concurrency:
  group: build-test-branch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-project:
    uses: ./.github/workflows/part_node_build.yaml
    secrets: inherit
    with:
      project: .

  docker-image:
    needs: [node-project]
    uses: ./.github/workflows/part_docker_build.yaml
    with:
      image_name: platzler-heid

  image-test:
    needs: [docker-image]
    uses: ./.github/workflows/part_docker_test.yaml
    with:
      artifact_name: ${{ needs.docker-image.outputs.artifact_name }}
      image_name: platzler-heid
      env_vars: >-
        -e NODE_ENV=production
        -e SCRAPE_INTERVAL_MIN=0
